// Generated by npm run source:api; do not edit
// Native members are complete for the recorded binary; unknown signatures stay unknown

export type UnverifiedNativeMethod = (...args: unknown[]) => unknown;

export const AiChatActivitySource = {
	AiChat: "AiChat",
	AiChatTitle: "AiChatTitle",
	AiCommand: "AiCommand",
	EmojiSearch: "EmojiSearch",
	QuickAi: "QuickAi",
} as const;
export type AiChatActivitySource =
	(typeof AiChatActivitySource)[keyof typeof AiChatActivitySource];

export const AiChatActivityType = {
	AssistantMessage: "AssistantMessage",
	UserMessage: "UserMessage",
} as const;
export type AiChatActivityType =
	(typeof AiChatActivityType)[keyof typeof AiChatActivityType];

export const AiErrorCode = {
	BranchError: 12001,
} as const;
export type AiErrorCode = (typeof AiErrorCode)[keyof typeof AiErrorCode];

export const AiRunErrorCode = {
	AdmissionConflict: 20005,
	CapacityExceeded: 20006,
	ContinuationPredecessorInvalid: 20007,
	CursorConflict: 20003,
	CursorNotContiguous: 20002,
	InputCommandConflict: 20004,
	JournalOwnershipLost: 20001,
	SupersedeHistoryChanged: 20008,
	TerminalPhaseConflict: 20009,
} as const;
export type AiRunErrorCode =
	(typeof AiRunErrorCode)[keyof typeof AiRunErrorCode];

export const AiSettledRunProjectionResult = {
	Projected: "projected",
	ProjectedCreated: "projectedCreated",
	SkippedAlreadyProjected: "skippedAlreadyProjected",
	SkippedDeleted: "skippedDeleted",
} as const;
export type AiSettledRunProjectionResult =
	(typeof AiSettledRunProjectionResult)[keyof typeof AiSettledRunProjectionResult];

export const AppIndexContentType = {
	App: 0,
	Game: 2,
	Preference: 1,
} as const;
export type AppIndexContentType =
	(typeof AppIndexContentType)[keyof typeof AppIndexContentType];

export const CalculatorErrorCode = {
	EntryNotFound: 15001,
	InvalidUpdate: 15002,
} as const;
export type CalculatorErrorCode =
	(typeof CalculatorErrorCode)[keyof typeof CalculatorErrorCode];

export const ClipboardErrorCode = {
	DateTimeFormat: 3008,
	ExhaustedIds: 3005,
	InvalidContentType: 3002,
	InvalidDateTimeString: 3004,
	InvalidEntryId: 3001,
	InvalidSourceHost: 3003,
	NoSuchEntry: 3006,
	NoSuchFilter: 3007,
} as const;
export type ClipboardErrorCode =
	(typeof ClipboardErrorCode)[keyof typeof ClipboardErrorCode];

export const ClipboardSourceHost = {
	iOS: "iOS",
	MacOS: "MacOS",
	Windows: "Windows",
} as const;
export type ClipboardSourceHost =
	(typeof ClipboardSourceHost)[keyof typeof ClipboardSourceHost];

export const CloudSyncActivityKind = {
	Importing: "Importing",
	Reconciling: "Reconciling",
} as const;
export type CloudSyncActivityKind =
	(typeof CloudSyncActivityKind)[keyof typeof CloudSyncActivityKind];

export const CloudSyncAuthFailureKind = {
	AuthFailed: "AuthFailed",
	AuthUserMismatch: "AuthUserMismatch",
} as const;
export type CloudSyncAuthFailureKind =
	(typeof CloudSyncAuthFailureKind)[keyof typeof CloudSyncAuthFailureKind];

export const CloudSyncDeviceDrainBlocker = {
	BridgeEnrollment: "BridgeEnrollment",
	BridgeImport: "BridgeImport",
	BridgeReconcile: "BridgeReconcile",
	BridgeV1ToV2: "BridgeV1ToV2",
	DeviceShape: "DeviceShape",
	EntityConvergence: "EntityConvergence",
	SessionOwner: "SessionOwner",
	ShapeBackfill: "ShapeBackfill",
	ShapeBackfillFailed: "ShapeBackfillFailed",
	StaleEntities: "StaleEntities",
} as const;
export type CloudSyncDeviceDrainBlocker =
	(typeof CloudSyncDeviceDrainBlocker)[keyof typeof CloudSyncDeviceDrainBlocker];

export const CloudSyncDeviceDrainStatus = {
	Pending: "Pending",
	Reached: "Reached",
	Unsupported: "Unsupported",
} as const;
export type CloudSyncDeviceDrainStatus =
	(typeof CloudSyncDeviceDrainStatus)[keyof typeof CloudSyncDeviceDrainStatus];

export const CloudSyncEnvironment = {
	Custom: "custom",
	Production: "production",
	Staging: "staging",
} as const;
export type CloudSyncEnvironment =
	(typeof CloudSyncEnvironment)[keyof typeof CloudSyncEnvironment];

export const CloudSyncErrorKind = {
	Auth: "Auth",
	Cancelled: "Cancelled",
	CertificateUntrusted: "CertificateUntrusted",
	Database: "Database",
	Network: "Network",
	Server: "Server",
	Timeout: "Timeout",
	UpgradeRequired: "UpgradeRequired",
} as const;
export type CloudSyncErrorKind =
	(typeof CloudSyncErrorKind)[keyof typeof CloudSyncErrorKind];

export const CloudSyncFlavor = {
	Development: "Development",
	Internal: "Internal",
	Production: "Production",
} as const;
export type CloudSyncFlavor =
	(typeof CloudSyncFlavor)[keyof typeof CloudSyncFlavor];

export const CloudSyncOperationType = {
	DELETE: "DELETE",
	PUT: "PUT",
} as const;
export type CloudSyncOperationType =
	(typeof CloudSyncOperationType)[keyof typeof CloudSyncOperationType];

export const CloudSyncPhase = {
	Connecting: "Connecting",
	Idle: "Idle",
	InitialSync: "InitialSync",
	Offline: "Offline",
	Online: "Online",
} as const;
export type CloudSyncPhase =
	(typeof CloudSyncPhase)[keyof typeof CloudSyncPhase];

export const ContentType = {
	Blob: "blob",
	Text: "text",
	Url: "url",
} as const;
export type ContentType = (typeof ContentType)[keyof typeof ContentType];

export const ControlKey = {
	ArrowDown: "ArrowDown",
	ArrowLeft: "ArrowLeft",
	ArrowRight: "ArrowRight",
	ArrowUp: "ArrowUp",
	Backspace: "Backspace",
	CapsLock: "CapsLock",
	Delete: "Delete",
	End: "End",
	Enter: "Enter",
	Escape: "Escape",
	F1: "F1",
	F10: "F10",
	F11: "F11",
	F12: "F12",
	F13: "F13",
	F14: "F14",
	F15: "F15",
	F16: "F16",
	F17: "F17",
	F18: "F18",
	F19: "F19",
	F2: "F2",
	F20: "F20",
	F21: "F21",
	F22: "F22",
	F23: "F23",
	F24: "F24",
	F3: "F3",
	F4: "F4",
	F5: "F5",
	F6: "F6",
	F7: "F7",
	F8: "F8",
	F9: "F9",
	Home: "Home",
	Insert: "Insert",
	NumpadDelete: "NumpadDelete",
	NumpadEnd: "NumpadEnd",
	NumpadEnter: "NumpadEnter",
	NumpadHome: "NumpadHome",
	NumpadInsert: "NumpadInsert",
	NumpadPageDown: "NumpadPageDown",
	NumpadPageUp: "NumpadPageUp",
	PageDown: "PageDown",
	PageUp: "PageUp",
	Tab: "Tab",
} as const;
export type ControlKey = (typeof ControlKey)[keyof typeof ControlKey];

export const CurrencyErrorCode = {
	InvalidValueType: 6001,
} as const;
export type CurrencyErrorCode =
	(typeof CurrencyErrorCode)[keyof typeof CurrencyErrorCode];

export const DatabaseErrorCode = {
	BackupDirectoryCreationFailed: 1020,
	BackupDirectoryListingFailed: 1021,
	CannotReadDatabase: 1016,
	CouldNotAttach: 1009,
	CouldNotDetach: 1010,
	DatabaseLockFailed: 1012,
	DatabaseNotInitialized: 1011,
	EncryptionKeyError: 1014,
	EncryptionKeyMismatch: 1023,
	InvalidAttach: 1007,
	InvalidPath: 1013,
	IoError: 1022,
	MigrationDivergent: 1005,
	MigrationError: 1003,
	MigrationMissing: 1004,
	NoBackupFound: 1025,
	NoEncryptionKey: 1015,
	OpenError: 1001,
	PathDoesNotExist: 1018,
	PathIsNotFolder: 1019,
	PostInitHook: 1008,
	PragmaError: 1002,
	ResetDatabaseFailed: 1026,
	RestoreFromBackupFailed: 1024,
	RusqliteError: 1006,
	SanityCheckFailed: 1017,
} as const;
export type DatabaseErrorCode =
	(typeof DatabaseErrorCode)[keyof typeof DatabaseErrorCode];

export const DatabaseKind = {
	Ai: "Ai",
	AppIndex: "AppIndex",
	Clipboard: "Clipboard",
	Emoji: "Emoji",
	Frecency: "Frecency",
	Main: "Main",
	NodeExtensions: "NodeExtensions",
	Screenshots: "Screenshots",
	Settings: "Settings",
	SettingsV2: "SettingsV2",
	UserActivity: "UserActivity",
} as const;
export type DatabaseKind = (typeof DatabaseKind)[keyof typeof DatabaseKind];

export const DataErrorCode = {
	DatabaseCorrupt: 2002,
	DatabaseLockFailed: 2007,
	DatabaseNotInitialized: 2008,
	JsonSerializationError: 2004,
	PinOpError: 2005,
	QueryError: 2001,
	SanityCheckFailed: 2006,
	SerializationError: 2003,
} as const;
export type DataErrorCode = (typeof DataErrorCode)[keyof typeof DataErrorCode];

export const Directionality = {
	left: "left",
	right: "right",
} as const;
export type Directionality =
	(typeof Directionality)[keyof typeof Directionality];

export const EmojiErrorCode = {
	ImportParseError: 8001,
	InvalidEmojiId: 8002,
} as const;
export type EmojiErrorCode =
	(typeof EmojiErrorCode)[keyof typeof EmojiErrorCode];

export const FaviconProvider = {
	DuckDuckGo: "duckduckgo",
	Google: "google",
	Local: "local",
	None: "none",
	Raycast: "raycast",
} as const;
export type FaviconProvider =
	(typeof FaviconProvider)[keyof typeof FaviconProvider];

export const FocusCategoryErrorCode = {
	InvalidKind: 19201,
	InvalidUlid: 19203,
	NotFound: 19202,
} as const;
export type FocusCategoryErrorCode =
	(typeof FocusCategoryErrorCode)[keyof typeof FocusCategoryErrorCode];

export const GeneralSettingsColumn = {
	AdditionalCertificateAuthorities: "AdditionalCertificateAuthorities",
	Appearance: "Appearance",
	BuiltinHotkeysPreset: "BuiltinHotkeysPreset",
	EnforcedInputSourceId: "EnforcedInputSourceId",
	EscapeKeyBehavior: "EscapeKeyBehavior",
	EscapeKeyClosesWindow: "EscapeKeyClosesWindow",
	FaviconProvider: "FaviconProvider",
	GlobalHotkey: "GlobalHotkey",
	HyperKeyCapsLockAction: "HyperKeyCapsLockAction",
	HyperKeyCode: "HyperKeyCode",
	HyperKeyDisplayShortcut: "HyperKeyDisplayShortcut",
	HyperKeyIncludeShift: "HyperKeyIncludeShift",
	NavigationBindings: "NavigationBindings",
	OpenAtLogin: "OpenAtLogin",
	OpenFoldersInTabs: "OpenFoldersInTabs",
	PageNavigationKeys: "PageNavigationKeys",
	PopToRootTimeout: "PopToRootTimeout",
	RootSearchSensitivity: "RootSearchSensitivity",
	ShowFavoritesInCompactMode: "ShowFavoritesInCompactMode",
	ShowInMenuBar: "ShowInMenuBar",
	ThemeDarkId: "ThemeDarkId",
	ThemeLightId: "ThemeLightId",
	TidyMenuBar: "TidyMenuBar",
	UiZoom: "UiZoom",
	UseSpotlightGesture: "UseSpotlightGesture",
	UseSystemProxySettings: "UseSystemProxySettings",
	WindowActivationBehavior: "WindowActivationBehavior",
	WindowMode: "WindowMode",
	WindowPresentationMode: "WindowPresentationMode",
} as const;
export type GeneralSettingsColumn =
	(typeof GeneralSettingsColumn)[keyof typeof GeneralSettingsColumn];

export const HyperKeyCapsLockAction = {
	trigger_escape: "trigger_escape",
	trigger_key: "trigger_key",
} as const;
export type HyperKeyCapsLockAction =
	(typeof HyperKeyCapsLockAction)[keyof typeof HyperKeyCapsLockAction];

export const HyperKeyCode = {
	caps_lock: "caps_lock",
	copilot: "copilot",
	f1: "f1",
	f10: "f10",
	f11: "f11",
	f12: "f12",
	f2: "f2",
	f3: "f3",
	f4: "f4",
	f5: "f5",
	f6: "f6",
	f7: "f7",
	f8: "f8",
	f9: "f9",
	left_command: "left_command",
	left_control: "left_control",
	left_option: "left_option",
	left_shift: "left_shift",
	right_command: "right_command",
	right_control: "right_control",
	right_option: "right_option",
	right_shift: "right_shift",
} as const;
export type HyperKeyCode = (typeof HyperKeyCode)[keyof typeof HyperKeyCode];

export const KeyboardShortcutLocality = {
	Global: "Global",
	Local: "Local",
} as const;
export type KeyboardShortcutLocality =
	(typeof KeyboardShortcutLocality)[keyof typeof KeyboardShortcutLocality];

export const MigrationErrorKind = {
	Config: "Config",
	Connection: "Connection",
	Divergent: "Divergent",
	InvalidFile: "InvalidFile",
	InvalidName: "InvalidName",
	InvalidPath: "InvalidPath",
	InvalidVersion: "InvalidVersion",
	Missing: "Missing",
	Repeated: "Repeated",
} as const;
export type MigrationErrorKind =
	(typeof MigrationErrorKind)[keyof typeof MigrationErrorKind];

export const ModifierKey = {
	Alt: "Alt",
	Ctrl: "Ctrl",
	Fn: "Fn",
	Meta: "Meta",
	Shift: "Shift",
} as const;
export type ModifierKey = (typeof ModifierKey)[keyof typeof ModifierKey];

export const NodeExtensionsErrorCode = {
	CommandNotFound: 11003,
	ExtensionNotFound: 11002,
	InvalidColumn: 11001,
	ToolNotFound: 11004,
} as const;
export type NodeExtensionsErrorCode =
	(typeof NodeExtensionsErrorCode)[keyof typeof NodeExtensionsErrorCode];

export const NoteErrorCode = {
	InvalidNoteId: 14001,
	InvalidUpdate: 14002,
	NoteNotFound: 14003,
	UpdateConflict: 14004,
} as const;
export type NoteErrorCode = (typeof NoteErrorCode)[keyof typeof NoteErrorCode];

export const OrgPackErrorCode = {
	KeywordLengthLimitExceeded: 13001,
} as const;
export type OrgPackErrorCode =
	(typeof OrgPackErrorCode)[keyof typeof OrgPackErrorCode];

export const PendingTokenErrorCode = {
	InvalidUpdate: 13001,
	PendingTokenNotFound: 13002,
} as const;
export type PendingTokenErrorCode =
	(typeof PendingTokenErrorCode)[keyof typeof PendingTokenErrorCode];

export const Platform = {
	Macos: "macos",
	Windows: "windows",
} as const;
export type Platform = (typeof Platform)[keyof typeof Platform];

export const QuickLinkErrorCode = {
	InvalidQuickLinkId: 10001,
	InvalidUpdate: 10002,
	QuickLinkNotFound: 10003,
	TagNotFound: 10004,
} as const;
export type QuickLinkErrorCode =
	(typeof QuickLinkErrorCode)[keyof typeof QuickLinkErrorCode];

export const ScreenshotCategory = {
	ScreenCapture: "ScreenCapture",
	ScreenRecording: "ScreenRecording",
} as const;
export type ScreenshotCategory =
	(typeof ScreenshotCategory)[keyof typeof ScreenshotCategory];

export const ScreenshotErrorCode = {
	DuplicatePath: 17003,
	InvalidCategory: 17001,
	ScreenshotNotFound: 17002,
} as const;
export type ScreenshotErrorCode =
	(typeof ScreenshotErrorCode)[keyof typeof ScreenshotErrorCode];

export const SettingsErrorCode = {
	InvalidColumn: 5001,
} as const;
export type SettingsErrorCode =
	(typeof SettingsErrorCode)[keyof typeof SettingsErrorCode];

export const SnippetErrorCode = {
	ContentLengthLimitExceeded: 9003,
	InvalidSnippetId: 9001,
	InvalidUlid: 9007,
	InvalidUpdate: 9004,
	KeywordLengthLimitExceeded: 9002,
	SnippetNotFound: 9005,
	TagNotFound: 9006,
} as const;
export type SnippetErrorCode =
	(typeof SnippetErrorCode)[keyof typeof SnippetErrorCode];

export const SyncAgentColumnStrategy = {
	GCounter: "GCounter",
	LWW: "LWW",
	ORSet: "ORSet",
	PNCounter: "PNCounter",
} as const;
export type SyncAgentColumnStrategy =
	(typeof SyncAgentColumnStrategy)[keyof typeof SyncAgentColumnStrategy];

export const TranslateCustomCommandErrorCode = {
	InvalidId: 19001,
	NotFound: 19002,
} as const;
export type TranslateCustomCommandErrorCode =
	(typeof TranslateCustomCommandErrorCode)[keyof typeof TranslateCustomCommandErrorCode];

export const UserActivityErrorCode = {
	InvalidYear: 13001,
} as const;
export type UserActivityErrorCode =
	(typeof UserActivityErrorCode)[keyof typeof UserActivityErrorCode];

export const UserActivityType = {
	AppClose: "AppClose",
	AppOpen: "AppOpen",
	InjectSnippet: "InjectSnippet",
	OpenAIChatPreset: "OpenAIChatPreset",
	OpenPreferences: "OpenPreferences",
	OpenRaycastCommand: "OpenRaycastCommand",
	OpenSystemApp: "OpenSystemApp",
	OpenWorkflow: "OpenWorkflow",
	StoreInstallExtension: "StoreInstallExtension",
	UseSnippet: "UseSnippet",
} as const;
export type UserActivityType =
	(typeof UserActivityType)[keyof typeof UserActivityType];

export const UserDefaultsErrorCode = {
	InvalidValueType: 4001,
} as const;
export type UserDefaultsErrorCode =
	(typeof UserDefaultsErrorCode)[keyof typeof UserDefaultsErrorCode];

export const WindowManagementErrorCode = {
	GroupNotFound: 18003,
	InvalidId: 18001,
	InvalidUpdate: 18002,
} as const;
export type WindowManagementErrorCode =
	(typeof WindowManagementErrorCode)[keyof typeof WindowManagementErrorCode];

export const WindowsRunCommandErrorCode = {
	InvalidId: 10001,
	InvalidUlid: 10005,
	InvalidUpdate: 10002,
	NotFound: 10003,
	TagNotFound: 10004,
} as const;
export type WindowsRunCommandErrorCode =
	(typeof WindowsRunCommandErrorCode)[keyof typeof WindowsRunCommandErrorCode];

export type NativeAiPickerUsageRepository = {
	listUsage: UnverifiedNativeMethod;
	recordUse: UnverifiedNativeMethod;
};

export type NativeAiRepository = {
	chatBranch: UnverifiedNativeMethod;
	chatClearConversation: UnverifiedNativeMethod;
	chatDeleteAll: UnverifiedNativeMethod;
	chatDeleteAllUnpinned: UnverifiedNativeMethod;
	chatDeleteOne: UnverifiedNativeMethod;
	chatGetAll: UnverifiedNativeMethod;
	chatGetAllByFolderId: UnverifiedNativeMethod;
	chatGetAllIds: UnverifiedNativeMethod;
	chatGetAllInvalidationSnapshots: UnverifiedNativeMethod;
	chatGetAllTitles: UnverifiedNativeMethod;
	chatGetChildPage: UnverifiedNativeMethod;
	chatGetCommandMessageByChatId: UnverifiedNativeMethod;
	chatGetConversationPage: UnverifiedNativeMethod;
	chatGetFilteredPage: UnverifiedNativeMethod;
	chatGetOne: UnverifiedNativeMethod;
	chatGetOneByMessageId: UnverifiedNativeMethod;
	chatGetOptional: UnverifiedNativeMethod;
	chatGetPage: UnverifiedNativeMethod;
	chatGetPageAfterId: UnverifiedNativeMethod;
	chatGetPinned: UnverifiedNativeMethod;
	chatGetRecentUpdatedBefore: UnverifiedNativeMethod;
	chatMessageDeleteMany: UnverifiedNativeMethod;
	chatMessageGetAll: UnverifiedNativeMethod;
	chatMessageGetAllByChatId: UnverifiedNativeMethod;
	chatMessageGetAllByRequestId: UnverifiedNativeMethod;
	chatMessageGetMemoryCandidates: UnverifiedNativeMethod;
	chatMessageGetPageAfterId: UnverifiedNativeMethod;
	chatMessageSearchByKeywords: UnverifiedNativeMethod;
	chatMessageSearchByTime: UnverifiedNativeMethod;
	chatMessageUpsertMany: UnverifiedNativeMethod;
	chatMessageUpsertOne: UnverifiedNativeMethod;
	chatRequestDeleteOne: UnverifiedNativeMethod;
	chatRequestGetAllByChatId: UnverifiedNativeMethod;
	chatRequestGetOne: UnverifiedNativeMethod;
	chatRequestGetPageAfterId: UnverifiedNativeMethod;
	chatRequestUpsertOne: UnverifiedNativeMethod;
	chatTouchUpdatedAt: UnverifiedNativeMethod;
	chatUpsertMany: UnverifiedNativeMethod;
	chatUpsertOne: UnverifiedNativeMethod;
	commandChatIdsForChatIds: UnverifiedNativeMethod;
	commandDeleteAll: UnverifiedNativeMethod;
	commandDeleteOne: UnverifiedNativeMethod;
	commandGetAll: UnverifiedNativeMethod;
	commandGetAllTags: UnverifiedNativeMethod;
	commandGetOne: UnverifiedNativeMethod;
	commandUpsertMany: UnverifiedNativeMethod;
	commandUpsertOne: UnverifiedNativeMethod;
	folderDeleteAll: UnverifiedNativeMethod;
	folderDeleteOne: UnverifiedNativeMethod;
	folderDeleteOneAndUnassignChats: UnverifiedNativeMethod;
	folderGetAll: UnverifiedNativeMethod;
	folderGetOne: UnverifiedNativeMethod;
	folderGetWorkingDirectory: UnverifiedNativeMethod;
	folderSetWorkingDirectory: UnverifiedNativeMethod;
	folderUpdateMemory: UnverifiedNativeMethod;
	folderUpsertOne: UnverifiedNativeMethod;
	modeDeleteAll: UnverifiedNativeMethod;
	modeDeleteOne: UnverifiedNativeMethod;
	modeGetAll: UnverifiedNativeMethod;
	modeGetOne: UnverifiedNativeMethod;
	modelDefaultGetAll: UnverifiedNativeMethod;
	modelDefaultUpsertOne: UnverifiedNativeMethod;
	modelGetAll: UnverifiedNativeMethod;
	modelGetById: UnverifiedNativeMethod;
	modelSetDisabledAt: UnverifiedNativeMethod;
	modelUpsertOne: UnverifiedNativeMethod;
	modeUpsertMany: UnverifiedNativeMethod;
	modeUpsertOne: UnverifiedNativeMethod;
	movePinnedDown: UnverifiedNativeMethod;
	movePinnedUp: UnverifiedNativeMethod;
	pinOne: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	scheduledMessageDeleteOccurrence: UnverifiedNativeMethod;
	scheduledMessageDeleteOne: UnverifiedNativeMethod;
	scheduledMessageGetAll: UnverifiedNativeMethod;
	scheduledMessageGetOne: UnverifiedNativeMethod;
	scheduledMessageUpdateOccurrence: UnverifiedNativeMethod;
	scheduledMessageUpsertOne: UnverifiedNativeMethod;
	transcriptionBackfillMissingRawValues: UnverifiedNativeMethod;
	transcriptionBackfillMissingStats: UnverifiedNativeMethod;
	transcriptionDeleteAll: UnverifiedNativeMethod;
	transcriptionDeleteOne: UnverifiedNativeMethod;
	transcriptionGetAll: UnverifiedNativeMethod;
	transcriptionGetPage: UnverifiedNativeMethod;
	transcriptionGetPageAfterId: UnverifiedNativeMethod;
	transcriptionGetStats: UnverifiedNativeMethod;
	transcriptionStyleDeleteAll: UnverifiedNativeMethod;
	transcriptionStyleDeleteOne: UnverifiedNativeMethod;
	transcriptionStyleGetAll: UnverifiedNativeMethod;
	transcriptionStyleGetAllTags: UnverifiedNativeMethod;
	transcriptionStyleGetOne: UnverifiedNativeMethod;
	transcriptionStyleGetPage: UnverifiedNativeMethod;
	transcriptionStyleUpsertMany: UnverifiedNativeMethod;
	transcriptionStyleUpsertOne: UnverifiedNativeMethod;
	transcriptionUpsertOne: UnverifiedNativeMethod;
	unpinOne: UnverifiedNativeMethod;
};

export type NativeAiRunsRepository = {
	abandonDeferredAdmission: UnverifiedNativeMethod;
	abandonRunInput: UnverifiedNativeMethod;
	abandonRunInputs: UnverifiedNativeMethod;
	acquireJournalOwnership: UnverifiedNativeMethod;
	applyRunEvent: UnverifiedNativeMethod;
	applyRunEvents: UnverifiedNativeMethod;
	backfillChatMessageSearch: UnverifiedNativeMethod;
	compareAndSwapSessionAgentState: UnverifiedNativeMethod;
	compressTurnProjections: UnverifiedNativeMethod;
	continueRun: UnverifiedNativeMethod;
	countNonterminalRuns: UnverifiedNativeMethod;
	countPendingDeferredAdmissions: UnverifiedNativeMethod;
	createSession: UnverifiedNativeMethod;
	deleteRunRecovery: UnverifiedNativeMethod;
	deleteSessionData: UnverifiedNativeMethod;
	editPendingRunInput: UnverifiedNativeMethod;
	enqueueDeferredAdmission: UnverifiedNativeMethod;
	enqueueOutbox: UnverifiedNativeMethod;
	eventsSince: UnverifiedNativeMethod;
	findAdmission: UnverifiedNativeMethod;
	findTurnProjectionLegacyRequests: UnverifiedNativeMethod;
	getChatMessageSearchBackfillProgress: UnverifiedNativeMethod;
	getDeferredAdmission: UnverifiedNativeMethod;
	getMaxSessionPin: UnverifiedNativeMethod;
	getRun: UnverifiedNativeMethod;
	getRunInput: UnverifiedNativeMethod;
	getRunRecovery: UnverifiedNativeMethod;
	getSessionAgent: UnverifiedNativeMethod;
	getSessionAgentState: UnverifiedNativeMethod;
	getSessionOrigin: UnverifiedNativeMethod;
	getSessionShell: UnverifiedNativeMethod;
	getTurnProjection: UnverifiedNativeMethod;
	incrementRecoveryAttempts: UnverifiedNativeMethod;
	insertLateToolResult: UnverifiedNativeMethod;
	leaseNextDeferredAdmission: UnverifiedNativeMethod;
	listAllSessionShells: UnverifiedNativeMethod;
	listArchivableSessionIds: UnverifiedNativeMethod;
	listArchivedSessionShells: UnverifiedNativeMethod;
	listChildRuns: UnverifiedNativeMethod;
	listDeletedSessionIds: UnverifiedNativeMethod;
	listDeletedSessionShells: UnverifiedNativeMethod;
	listFolderSessionShells: UnverifiedNativeMethod;
	listInterruptedRuns: UnverifiedNativeMethod;
	listLateToolResults: UnverifiedNativeMethod;
	listOrganizedSessionShells: UnverifiedNativeMethod;
	listOutboxForRun: UnverifiedNativeMethod;
	listPendingDeferredAdmissions: UnverifiedNativeMethod;
	listPendingOutbox: UnverifiedNativeMethod;
	listPendingRunInputs: UnverifiedNativeMethod;
	listPinnedSessionShells: UnverifiedNativeMethod;
	listRunRecovery: UnverifiedNativeMethod;
	listRuns: UnverifiedNativeMethod;
	listRunsAwaitingProjection: UnverifiedNativeMethod;
	listRunsRetainingQueue: UnverifiedNativeMethod;
	listSessionRootRuns: UnverifiedNativeMethod;
	listSessionShells: UnverifiedNativeMethod;
	listSupersededTurnProjectionRunIds: UnverifiedNativeMethod;
	listSuspendedRuns: UnverifiedNativeMethod;
	listTurnProjectionRunIds: UnverifiedNativeMethod;
	listTurnProjections: UnverifiedNativeMethod;
	listTurnProjectionsPendingSearchIndex: UnverifiedNativeMethod;
	listTurnSearchText: UnverifiedNativeMethod;
	markNonTimelineTurnProjectionsSearchIndexed: UnverifiedNativeMethod;
	markRunInputApplied: UnverifiedNativeMethod;
	markRunProjected: UnverifiedNativeMethod;
	markTurnProjectionSearchFailed: UnverifiedNativeMethod;
	projectSettledRun: UnverifiedNativeMethod;
	pruneJournal: UnverifiedNativeMethod;
	releaseDeferredAdmissionLease: UnverifiedNativeMethod;
	reorderPendingRunInputs: UnverifiedNativeMethod;
	repairSessionActivity: UnverifiedNativeMethod;
	replaceTurnProjectionLegacyRequests: UnverifiedNativeMethod;
	replaceTurnSearchText: UnverifiedNativeMethod;
	reserveAdmission: UnverifiedNativeMethod;
	reserveRunInput: UnverifiedNativeMethod;
	resolveDeferredAdmission: UnverifiedNativeMethod;
	resolveOutbox: UnverifiedNativeMethod;
	searchSessionShells: UnverifiedNativeMethod;
	searchSessionShellsWithContent: UnverifiedNativeMethod;
	setSessionArchived: UnverifiedNativeMethod;
	setSessionDeleted: UnverifiedNativeMethod;
	setSessionFolder: UnverifiedNativeMethod;
	setSessionOrigin: UnverifiedNativeMethod;
	setSessionPinned: UnverifiedNativeMethod;
	softDeleteUnpinnedSessions: UnverifiedNativeMethod;
	steerPendingRunInput: UnverifiedNativeMethod;
	supersedeRun: UnverifiedNativeMethod;
	touchSession: UnverifiedNativeMethod;
	transferPendingRunInput: UnverifiedNativeMethod;
	turnProjectionStorageStats: UnverifiedNativeMethod;
	upsertRunRecovery: UnverifiedNativeMethod;
	upsertTurnProjection: UnverifiedNativeMethod;
};

export type NativeAiToolUsageRepository = {
	recordToolUse: UnverifiedNativeMethod;
	topTools: UnverifiedNativeMethod;
};

export type NativeAppIndexRepository = {
	deleteByRaycastId: UnverifiedNativeMethod;
	deleteManyByRaycastId: UnverifiedNativeMethod;
	getAllByContentType: UnverifiedNativeMethod;
	getAllBySystemContentType: UnverifiedNativeMethod;
	getByPath: UnverifiedNativeMethod;
	hasAnyByContentType: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	setUserContentType: UnverifiedNativeMethod;
	upsert: UnverifiedNativeMethod;
	upsertMany: UnverifiedNativeMethod;
};

export type NativeAppleShortcutsRepository = {
	all: UnverifiedNativeMethod;
	replaceAll: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
};

export type NativeAppMenuBarItemsRepository = {
	listPinned: UnverifiedNativeMethod;
	movePinnedDown: UnverifiedNativeMethod;
	movePinnedUp: UnverifiedNativeMethod;
	pin: UnverifiedNativeMethod;
	unpin: UnverifiedNativeMethod;
};

export type NativeCalculatorRepository = {
	all: UnverifiedNativeMethod;
	deleteAll: UnverifiedNativeMethod;
	deleteExceedingLimit: UnverifiedNativeMethod;
	deleteOlderThan: UnverifiedNativeMethod;
	deleteOne: UnverifiedNativeMethod;
	getOne: UnverifiedNativeMethod;
	movePinnedDown: UnverifiedNativeMethod;
	movePinnedUp: UnverifiedNativeMethod;
	pinOne: UnverifiedNativeMethod;
	unpinOne: UnverifiedNativeMethod;
	upsert: UnverifiedNativeMethod;
};

export type NativeClipboardRepository = {
	all: UnverifiedNativeMethod;
	deleteAll: UnverifiedNativeMethod;
	deleteAllAfterDate: UnverifiedNativeMethod;
	deleteAllBeforeDate: UnverifiedNativeMethod;
	deleteFilter: UnverifiedNativeMethod;
	deleteOne: UnverifiedNativeMethod;
	getAllFilters: UnverifiedNativeMethod;
	getAllTags: UnverifiedNativeMethod;
	getFilter: UnverifiedNativeMethod;
	getOne: UnverifiedNativeMethod;
	getOneByContentHash: UnverifiedNativeMethod;
	insertMany: UnverifiedNativeMethod;
	insertOne: UnverifiedNativeMethod;
	last: UnverifiedNativeMethod;
	movePinnedDown: UnverifiedNativeMethod;
	movePinnedUp: UnverifiedNativeMethod;
	pinOne: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	unpinOne: UnverifiedNativeMethod;
	updateOne: UnverifiedNativeMethod;
	upsertFilter: UnverifiedNativeMethod;
};

export type NativeContactsRepository = {
	all: UnverifiedNativeMethod;
	replaceAll: UnverifiedNativeMethod;
};

export type NativeCurrenciesRepository = {
	all: UnverifiedNativeMethod;
	deleteAllCrypto: UnverifiedNativeMethod;
	deleteAllFiat: UnverifiedNativeMethod;
	replaceCrypto: UnverifiedNativeMethod;
	replaceFiat: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	setCrypto: UnverifiedNativeMethod;
	setFiat: UnverifiedNativeMethod;
};

export type NativeDatabaseClient = {
	readonly ai: NativeAiRepository;
	readonly aiPickerUsage: NativeAiPickerUsageRepository;
	readonly aiRuns: NativeAiRunsRepository;
	readonly aiToolUsage: NativeAiToolUsageRepository;
	readonly appIndex: NativeAppIndexRepository;
	readonly appleShortcuts: NativeAppleShortcutsRepository;
	readonly appMenuBarItems: NativeAppMenuBarItemsRepository;
	backupDatabases: UnverifiedNativeMethod;
	readonly calculator: NativeCalculatorRepository;
	readonly clipboard: NativeClipboardRepository;
	readonly contacts: NativeContactsRepository;
	readonly currencies: NativeCurrenciesRepository;
	readonly effectiveEncryptionKey: unknown;
	readonly emoji: NativeEmojiRepository;
	readonly focusCategories: NativeFocusCategoriesRepository;
	readonly frecency: NativeFrecencyRepository;
	getDatabaseStatus: UnverifiedNativeMethod;
	readonly initReport: unknown;
	readonly nodeExtensions: NativeNodeExtensionsRepository;
	readonly notes: NativeNotesRepository;
	openDatabaseSnapshot: UnverifiedNativeMethod;
	readonly orgPacks: NativeOrgPacksRepository;
	readonly pendingTokens: NativePendingTokensRepository;
	readonly quicklinks: NativeQuicklinksRepository;
	resetDatabase: UnverifiedNativeMethod;
	restoreFromBackup: UnverifiedNativeMethod;
	readonly screenshots: NativeScreenshotsRepository;
	setDeviceId: UnverifiedNativeMethod;
	readonly settings: NativeSettingsRepository;
	shutdown: UnverifiedNativeMethod;
	readonly snippets: NativeSnippetsRepository;
	testHang: UnverifiedNativeMethod;
	readonly translateCustomCommands: NativeTranslateCustomCommandsRepository;
	readonly userActivity: NativeUserActivityRepository;
	readonly userDefaults: NativeUserDefaultsRepository;
	vacuum: UnverifiedNativeMethod;
	vacuumAll: UnverifiedNativeMethod;
	walCheckpoint: UnverifiedNativeMethod;
	walCheckpointAll: UnverifiedNativeMethod;
	readonly windowManagement: NativeWindowManagementRepository;
	readonly windowsRunCommands: NativeWindowsRunCommandsRepository;
};

export type NativeDatabaseSnapshot = {
	readonly ai: NativeAiRepository;
	readonly clipboard: NativeClipboardRepository;
	readonly emoji: NativeEmojiRepository;
	readonly focusCategories: NativeFocusCategoriesRepository;
	readonly frecency: NativeFrecencyRepository;
	readonly nodeExtensions: NativeNodeExtensionsRepository;
	readonly notes: NativeNotesRepository;
	readonly orgPacks: NativeOrgPacksRepository;
	readonly quicklinks: NativeQuicklinksRepository;
	release: UnverifiedNativeMethod;
	readonly settings: NativeSettingsRepository;
	readonly snippets: NativeSnippetsRepository;
	readonly userActivity: NativeUserActivityRepository;
	readonly userDefaults: NativeUserDefaultsRepository;
	readonly windowManagement: NativeWindowManagementRepository;
};

export type NativeEmojiRepository = {
	all: UnverifiedNativeMethod;
	getBySymbol: UnverifiedNativeMethod;
	movePinnedDown: UnverifiedNativeMethod;
	movePinnedUp: UnverifiedNativeMethod;
	pinOne: UnverifiedNativeMethod;
	resetFrecency: UnverifiedNativeMethod;
	restoreFrecency: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	setCustomKeywords: UnverifiedNativeMethod;
	unpinOne: UnverifiedNativeMethod;
	visit: UnverifiedNativeMethod;
};

export type NativeFocusCategoriesRepository = {
	deleteCustomByCategoryId: UnverifiedNativeMethod;
	getByCategoryId: UnverifiedNativeMethod;
	insertCustom: UnverifiedNativeMethod;
	list: UnverifiedNativeMethod;
	updateAccessedAtByCategoryId: UnverifiedNativeMethod;
	updateCustomByCategoryId: UnverifiedNativeMethod;
	upsertBuiltin: UnverifiedNativeMethod;
};

export type NativeFrecencyRepository = {
	getAll: UnverifiedNativeMethod;
	getAllByIds: UnverifiedNativeMethod;
	getRecords: UnverifiedNativeMethod;
	insertMany: UnverifiedNativeMethod;
	reset: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	search: UnverifiedNativeMethod;
	visit: UnverifiedNativeMethod;
};

export type NativeNodeExtensionsRepository = {
	addExtension: UnverifiedNativeMethod;
	addExtensionInstallHistory: UnverifiedNativeMethod;
	allCommands: UnverifiedNativeMethod;
	allExtensions: UnverifiedNativeMethod;
	allTools: UnverifiedNativeMethod;
	clearModelProviderDigest: UnverifiedNativeMethod;
	deleteExtension: UnverifiedNativeMethod;
	extensionIdsWithTools: UnverifiedNativeMethod;
	extensionsWithLocalSources: UnverifiedNativeMethod;
	getCommandById: UnverifiedNativeMethod;
	getCommandsByExtensionDatabaseId: UnverifiedNativeMethod;
	getDevelopmentExtensionByName: UnverifiedNativeMethod;
	getExtensionByDatabaseId: UnverifiedNativeMethod;
	getExtensionByExtensionId: UnverifiedNativeMethod;
	getExtensionInstallHistoryByUuid: UnverifiedNativeMethod;
	getStoreExtensionByName: UnverifiedNativeMethod;
	getToolById: UnverifiedNativeMethod;
	getToolsByExtensionDatabaseId: UnverifiedNativeMethod;
	hasAnyExtensions: UnverifiedNativeMethod;
	hasToolsByExtensionDatabaseId: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	updateCommandDigest: UnverifiedNativeMethod;
	updateExtension: UnverifiedNativeMethod;
	updateModelProviderDigest: UnverifiedNativeMethod;
	updateToolDigest: UnverifiedNativeMethod;
};

export type NativeNotesRepository = {
	browse: UnverifiedNativeMethod;
	count: UnverifiedNativeMethod;
	deleteAll: UnverifiedNativeMethod;
	deleteOne: UnverifiedNativeMethod;
	deleteOneImmediately: UnverifiedNativeMethod;
	emptyTrash: UnverifiedNativeMethod;
	getWindowData: UnverifiedNativeMethod;
	insertMany: UnverifiedNativeMethod;
	insertOne: UnverifiedNativeMethod;
	list: UnverifiedNativeMethod;
	listDeleted: UnverifiedNativeMethod;
	movePinnedDown: UnverifiedNativeMethod;
	movePinnedUp: UnverifiedNativeMethod;
	permanentlyDeleteOne: UnverifiedNativeMethod;
	pinOne: UnverifiedNativeMethod;
	purgeOldDeleted: UnverifiedNativeMethod;
	recoverOne: UnverifiedNativeMethod;
	replaceOne: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	touchAccessed: UnverifiedNativeMethod;
	unpinOne: UnverifiedNativeMethod;
	updateOne: UnverifiedNativeMethod;
};

export type NativeOrgPacksRepository = {
	clearAllOrgData: UnverifiedNativeMethod;
	clearLocalOrgQuicklinkTags: UnverifiedNativeMethod;
	clearLocalOrgSnippetKeyword: UnverifiedNativeMethod;
	clearLocalOrgSnippetTags: UnverifiedNativeMethod;
	clearLocalTranscriptionStyleApplicationIds: UnverifiedNativeMethod;
	deleteOrgAiAgent: UnverifiedNativeMethod;
	deleteOrgAiAgentsByPack: UnverifiedNativeMethod;
	deleteOrgAiCommand: UnverifiedNativeMethod;
	deleteOrgAiCommandsByPack: UnverifiedNativeMethod;
	deleteOrgDataNotInOrgIds: UnverifiedNativeMethod;
	deleteOrgQuicklink: UnverifiedNativeMethod;
	deleteOrgQuicklinksByPack: UnverifiedNativeMethod;
	deleteOrgQuicklinksNotIn: UnverifiedNativeMethod;
	deleteOrgSkill: UnverifiedNativeMethod;
	deleteOrgSkillsByPack: UnverifiedNativeMethod;
	deleteOrgSnippet: UnverifiedNativeMethod;
	deleteOrgSnippetsByPack: UnverifiedNativeMethod;
	deleteOrgSnippetsNotIn: UnverifiedNativeMethod;
	deleteOrgTranscriptionStyle: UnverifiedNativeMethod;
	deleteOrgTranscriptionStylesByPack: UnverifiedNativeMethod;
	getAllOrgQuicklinkTags: UnverifiedNativeMethod;
	getAllOrgSnippetTags: UnverifiedNativeMethod;
	getAllPinnedOrgQuicklinks: UnverifiedNativeMethod;
	getAllPinnedOrgSnippets: UnverifiedNativeMethod;
	getLocalOrgSnippetKeyword: UnverifiedNativeMethod;
	getLocalTranscriptionStyleApplicationIds: UnverifiedNativeMethod;
	getOrgAiAgentById: UnverifiedNativeMethod;
	getOrgAiCommandById: UnverifiedNativeMethod;
	getOrgQuicklinkById: UnverifiedNativeMethod;
	getOrgSkillById: UnverifiedNativeMethod;
	getOrgSnippetById: UnverifiedNativeMethod;
	getOrgSnippetKeywords: UnverifiedNativeMethod;
	getOrgSnippetsByTitle: UnverifiedNativeMethod;
	getOrgTranscriptionStyleById: UnverifiedNativeMethod;
	getSyncState: UnverifiedNativeMethod;
	listOrgAiAgents: UnverifiedNativeMethod;
	listOrgAiCommands: UnverifiedNativeMethod;
	listOrgQuicklinks: UnverifiedNativeMethod;
	listOrgSkills: UnverifiedNativeMethod;
	listOrgSnippets: UnverifiedNativeMethod;
	listOrgTranscriptionStyles: UnverifiedNativeMethod;
	pinOrgQuicklinkAt: UnverifiedNativeMethod;
	pinOrgSnippetAt: UnverifiedNativeMethod;
	reconcileOrgAiAgents: UnverifiedNativeMethod;
	reconcileOrgAiCommands: UnverifiedNativeMethod;
	reconcileOrgQuicklinks: UnverifiedNativeMethod;
	reconcileOrgSkills: UnverifiedNativeMethod;
	reconcileOrgSnippets: UnverifiedNativeMethod;
	reconcileOrgTranscriptionStyles: UnverifiedNativeMethod;
	setLocalOrgQuicklinkTags: UnverifiedNativeMethod;
	setLocalOrgSnippetKeyword: UnverifiedNativeMethod;
	setLocalOrgSnippetKeywordPreservingExistingContent: UnverifiedNativeMethod;
	setLocalOrgSnippetTags: UnverifiedNativeMethod;
	setLocalTranscriptionStyleApplicationIds: UnverifiedNativeMethod;
	setOrgSkillEnabled: UnverifiedNativeMethod;
	setSyncState: UnverifiedNativeMethod;
	unpinOrgQuicklink: UnverifiedNativeMethod;
	unpinOrgSnippet: UnverifiedNativeMethod;
	updateOrgSnippetAccessedAt: UnverifiedNativeMethod;
	upsertOrgAiAgents: UnverifiedNativeMethod;
	upsertOrgAiCommands: UnverifiedNativeMethod;
	upsertOrgQuicklinks: UnverifiedNativeMethod;
	upsertOrgSkills: UnverifiedNativeMethod;
	upsertOrgSnippets: UnverifiedNativeMethod;
	upsertOrgTranscriptionStyles: UnverifiedNativeMethod;
};

export type NativePendingTokensRepository = {
	all: UnverifiedNativeMethod;
	deleteOne: UnverifiedNativeMethod;
	insertOne: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	updateOne: UnverifiedNativeMethod;
};

export type NativeQuicklinksRepository = {
	count: UnverifiedNativeMethod;
	deleteAll: UnverifiedNativeMethod;
	deleteOne: UnverifiedNativeMethod;
	exportPlatformOpenWith: UnverifiedNativeMethod;
	getAllPinned: UnverifiedNativeMethod;
	getAllTags: UnverifiedNativeMethod;
	getOne: UnverifiedNativeMethod;
	importPlatformOpenWith: UnverifiedNativeMethod;
	insertMany: UnverifiedNativeMethod;
	insertOne: UnverifiedNativeMethod;
	list: UnverifiedNativeMethod;
	movePinnedDown: UnverifiedNativeMethod;
	movePinnedUp: UnverifiedNativeMethod;
	pinOne: UnverifiedNativeMethod;
	pinOneAt: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	unpinOne: UnverifiedNativeMethod;
	updateOne: UnverifiedNativeMethod;
	updateOpenCount: UnverifiedNativeMethod;
};

export type NativeScreenshotsRepository = {
	all: UnverifiedNativeMethod;
	allByCategory: UnverifiedNativeMethod;
	deleteAll: UnverifiedNativeMethod;
	deleteByPath: UnverifiedNativeMethod;
	deleteByPaths: UnverifiedNativeMethod;
	deleteOne: UnverifiedNativeMethod;
	getByPath: UnverifiedNativeMethod;
	getLatestByDate: UnverifiedNativeMethod;
	getUnpinnedOlderThan: UnverifiedNativeMethod;
	insertMany: UnverifiedNativeMethod;
	insertOne: UnverifiedNativeMethod;
	pinOne: UnverifiedNativeMethod;
	reorderPinned: UnverifiedNativeMethod;
	search: UnverifiedNativeMethod;
	unpinOne: UnverifiedNativeMethod;
	updateOne: UnverifiedNativeMethod;
	updateText: UnverifiedNativeMethod;
};

export type NativeSettingsRepository = {
	addCommandSettings: UnverifiedNativeMethod;
	addInternalExtensionSettings: UnverifiedNativeMethod;
	addNodeExtensionSettings: UnverifiedNativeMethod;
	addTheme: UnverifiedNativeMethod;
	allCommandSettings: UnverifiedNativeMethod;
	allCommandSettingsForExtension: UnverifiedNativeMethod;
	allCommandsWithStatusItems: UnverifiedNativeMethod;
	allInternalExtensionsSettings: UnverifiedNativeMethod;
	allMcpServers: UnverifiedNativeMethod;
	allNodeExtensionsSettings: UnverifiedNativeMethod;
	allThemes: UnverifiedNativeMethod;
	allWindowModes: UnverifiedNativeMethod;
	clearCommandDeprecatedHotkey: UnverifiedNativeMethod;
	clearCommandDeprecatedMeta: UnverifiedNativeMethod;
	clearInternalExtensionDeprecatedMeta: UnverifiedNativeMethod;
	clearNodeExtensionDeprecatedMeta: UnverifiedNativeMethod;
	deleteAllMcpServers: UnverifiedNativeMethod;
	deleteCommandSettings: UnverifiedNativeMethod;
	deleteInternalExtensionSettings: UnverifiedNativeMethod;
	deleteMcpServer: UnverifiedNativeMethod;
	deleteNodeExtensionSettings: UnverifiedNativeMethod;
	deleteTheme: UnverifiedNativeMethod;
	getCloudSyncSettings: UnverifiedNativeMethod;
	getCommandSettings: UnverifiedNativeMethod;
	getCommandSettingsByIds: UnverifiedNativeMethod;
	getGeneralSettings: UnverifiedNativeMethod;
	getIdentifierMigrationSnapshot: UnverifiedNativeMethod;
	getInternalExtensionSettings: UnverifiedNativeMethod;
	getNodeExtensionSettings: UnverifiedNativeMethod;
	getTheme: UnverifiedNativeMethod;
	migrateSettingsIdentifiers: UnverifiedNativeMethod;
	overrideCloudSyncConnection: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	setNodeExtensionUninstalled: UnverifiedNativeMethod;
	toggleCloudSyncCategory: UnverifiedNativeMethod;
	toggleCloudSyncSettings: UnverifiedNativeMethod;
	updateCommandRuntime: UnverifiedNativeMethod;
	updateCommandSettings: UnverifiedNativeMethod;
	updateCommandStatusItem: UnverifiedNativeMethod;
	updateGeneralSetting: UnverifiedNativeMethod;
	updateInternalExtensionSettings: UnverifiedNativeMethod;
	updateManyCommandSettings: UnverifiedNativeMethod;
	updateNodeExtensionSettings: UnverifiedNativeMethod;
	updateTheme: UnverifiedNativeMethod;
	upsertMcpServer: UnverifiedNativeMethod;
};

export type NativeSnippetsRepository = {
	count: UnverifiedNativeMethod;
	deleteAll: UnverifiedNativeMethod;
	deleteOne: UnverifiedNativeMethod;
	getAllPinned: UnverifiedNativeMethod;
	getAllTags: UnverifiedNativeMethod;
	getByTitle: UnverifiedNativeMethod;
	getKeywords: UnverifiedNativeMethod;
	getOne: UnverifiedNativeMethod;
	insertMany: UnverifiedNativeMethod;
	insertOne: UnverifiedNativeMethod;
	insertOnePreservingExistingContent: UnverifiedNativeMethod;
	list: UnverifiedNativeMethod;
	movePinnedDown: UnverifiedNativeMethod;
	movePinnedUp: UnverifiedNativeMethod;
	pinOne: UnverifiedNativeMethod;
	pinOneAt: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	unpinOne: UnverifiedNativeMethod;
	updateAccessedAt: UnverifiedNativeMethod;
	updateCopyCount: UnverifiedNativeMethod;
	updateOne: UnverifiedNativeMethod;
};

export type NativeSyncAgent = {
	destroyLocalState: UnverifiedNativeMethod;
	devices: UnverifiedNativeMethod;
	forwardDevices: UnverifiedNativeMethod;
	forwardEvents: UnverifiedNativeMethod;
	forwardStatus: UnverifiedNativeMethod;
	readonly isRunning: unknown;
	pauseForContention: UnverifiedNativeMethod;
	reconnectNow: UnverifiedNativeMethod;
	run: UnverifiedNativeMethod;
	readonly status: unknown;
	stop: UnverifiedNativeMethod;
};

export type NativeTranslateCustomCommandsRepository = {
	deleteOne: UnverifiedNativeMethod;
	getOne: UnverifiedNativeMethod;
	list: UnverifiedNativeMethod;
	save: UnverifiedNativeMethod;
	updateOne: UnverifiedNativeMethod;
};

export type NativeUserActivityRepository = {
	countActivitiesByTypeAndYear: UnverifiedNativeMethod;
	countActivitiesByTypeYearAndKeyPrefix: UnverifiedNativeMethod;
	countAiChatActivitiesBySourceAndYear: UnverifiedNativeMethod;
	countAiChatActivitiesBySourceTypeAndYear: UnverifiedNativeMethod;
	countAiChatActivitiesByTypeAndYear: UnverifiedNativeMethod;
	countAiChatActivitiesByYear: UnverifiedNativeMethod;
	countAiChatByModel: UnverifiedNativeMethod;
	deleteAllActivities: UnverifiedNativeMethod;
	deleteAllActivityInfo: UnverifiedNativeMethod;
	deleteAllAiChatActivities: UnverifiedNativeMethod;
	deleteAllFocusActivities: UnverifiedNativeMethod;
	getAllActivities: UnverifiedNativeMethod;
	getAllActivityInfo: UnverifiedNativeMethod;
	getAllAiChatActivities: UnverifiedNativeMethod;
	getAllFocusActivities: UnverifiedNativeMethod;
	getDailyActivityDistribution: UnverifiedNativeMethod;
	getHourlyActivityDistribution: UnverifiedNativeMethod;
	getLatestActivitiesByTypeAndYear: UnverifiedNativeMethod;
	getTopActivitiesByCount: UnverifiedNativeMethod;
	getTopActivitiesByCountAndKeyPrefix: UnverifiedNativeMethod;
	getTopAiChatModelsByYear: UnverifiedNativeMethod;
	importActivity: UnverifiedNativeMethod;
	importActivityInfo: UnverifiedNativeMethod;
	importAiChatActivity: UnverifiedNativeMethod;
	importFocusActivity: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	sumAiChatWordCountByTypeAndYear: UnverifiedNativeMethod;
	trackActivity: UnverifiedNativeMethod;
	trackAiChatActivity: UnverifiedNativeMethod;
	trackFocusActivity: UnverifiedNativeMethod;
};

export type NativeUserDefaultsRepository = {
	delete: UnverifiedNativeMethod;
	get: UnverifiedNativeMethod;
	sanityCheck: UnverifiedNativeMethod;
	set: UnverifiedNativeMethod;
};

export type NativeWindowManagementRepository = {
	deleteAll: UnverifiedNativeMethod;
	deleteOne: UnverifiedNativeMethod;
	exportPlatformSources: UnverifiedNativeMethod;
	getOne: UnverifiedNativeMethod;
	importPlatformSources: UnverifiedNativeMethod;
	insertMany: UnverifiedNativeMethod;
	list: UnverifiedNativeMethod;
	replaceOne: UnverifiedNativeMethod;
	save: UnverifiedNativeMethod;
	updateOne: UnverifiedNativeMethod;
};

export type NativeWindowsRunCommandsRepository = {
	all: UnverifiedNativeMethod;
	deleteAll: UnverifiedNativeMethod;
	deleteOne: UnverifiedNativeMethod;
	duplicate: UnverifiedNativeMethod;
	getAllTags: UnverifiedNativeMethod;
	getByAlias: UnverifiedNativeMethod;
	getByCommand: UnverifiedNativeMethod;
	getOne: UnverifiedNativeMethod;
	insertOne: UnverifiedNativeMethod;
	movePinnedDown: UnverifiedNativeMethod;
	movePinnedUp: UnverifiedNativeMethod;
	pinOne: UnverifiedNativeMethod;
	recordExecution: UnverifiedNativeMethod;
	unpinOne: UnverifiedNativeMethod;
	updateOne: UnverifiedNativeMethod;
};

export type NativeAddon = {
	AiChatActivitySource: typeof AiChatActivitySource;
	AiChatActivityType: typeof AiChatActivityType;
	AiErrorCode: typeof AiErrorCode;
	AiPickerUsageRepository: {
		new (...args: unknown[]): NativeAiPickerUsageRepository;
	};
	AiRepository: { new (...args: unknown[]): NativeAiRepository };
	AiRunErrorCode: typeof AiRunErrorCode;
	AiRunsRepository: { new (...args: unknown[]): NativeAiRunsRepository };
	AiSettledRunProjectionResult: typeof AiSettledRunProjectionResult;
	AiToolUsageRepository: {
		new (...args: unknown[]): NativeAiToolUsageRepository;
	};
	AppIndexContentType: typeof AppIndexContentType;
	AppIndexRepository: { new (...args: unknown[]): NativeAppIndexRepository };
	AppleShortcutsRepository: {
		new (...args: unknown[]): NativeAppleShortcutsRepository;
	};
	AppMenuBarItemsRepository: {
		new (...args: unknown[]): NativeAppMenuBarItemsRepository;
	};
	busyErrorCount: UnverifiedNativeMethod;
	CalculatorErrorCode: typeof CalculatorErrorCode;
	CalculatorRepository: {
		new (...args: unknown[]): NativeCalculatorRepository;
	};
	ClipboardErrorCode: typeof ClipboardErrorCode;
	ClipboardRepository: { new (...args: unknown[]): NativeClipboardRepository };
	ClipboardSourceHost: typeof ClipboardSourceHost;
	CloudSyncActivityKind: typeof CloudSyncActivityKind;
	cloudSyncApplyFailureDiagnosticSnapshot: UnverifiedNativeMethod;
	cloudSyncApplyFailureTelemetrySnapshot: UnverifiedNativeMethod;
	CloudSyncAuthFailureKind: typeof CloudSyncAuthFailureKind;
	CloudSyncDeviceDrainBlocker: typeof CloudSyncDeviceDrainBlocker;
	CloudSyncDeviceDrainStatus: typeof CloudSyncDeviceDrainStatus;
	CloudSyncEnvironment: typeof CloudSyncEnvironment;
	CloudSyncErrorKind: typeof CloudSyncErrorKind;
	CloudSyncFlavor: typeof CloudSyncFlavor;
	cloudSyncIdentityDiagnosticSnapshot: UnverifiedNativeMethod;
	CloudSyncOperationType: typeof CloudSyncOperationType;
	cloudSyncPendingOperationDiagnosticSnapshot: UnverifiedNativeMethod;
	CloudSyncPhase: typeof CloudSyncPhase;
	cloudSyncPushRejectionDiagnosticSnapshot: UnverifiedNativeMethod;
	ContactsRepository: { new (...args: unknown[]): NativeContactsRepository };
	ContentType: typeof ContentType;
	ControlKey: typeof ControlKey;
	createCloudSyncConnection: UnverifiedNativeMethod;
	CurrenciesRepository: {
		new (...args: unknown[]): NativeCurrenciesRepository;
	};
	CurrencyErrorCode: typeof CurrencyErrorCode;
	DatabaseClient: { new (...args: unknown[]): NativeDatabaseClient };
	DatabaseErrorCode: typeof DatabaseErrorCode;
	DatabaseKind: typeof DatabaseKind;
	DatabaseSnapshot: { new (...args: unknown[]): NativeDatabaseSnapshot };
	DataErrorCode: typeof DataErrorCode;
	Directionality: typeof Directionality;
	EmojiErrorCode: typeof EmojiErrorCode;
	EmojiRepository: { new (...args: unknown[]): NativeEmojiRepository };
	FaviconProvider: typeof FaviconProvider;
	FocusCategoriesRepository: {
		new (...args: unknown[]): NativeFocusCategoriesRepository;
	};
	FocusCategoryErrorCode: typeof FocusCategoryErrorCode;
	FrecencyRepository: { new (...args: unknown[]): NativeFrecencyRepository };
	GeneralSettingsColumn: typeof GeneralSettingsColumn;
	gracefulShutdownFinished: UnverifiedNativeMethod;
	HyperKeyCapsLockAction: typeof HyperKeyCapsLockAction;
	HyperKeyCode: typeof HyperKeyCode;
	KeyboardShortcutLocality: typeof KeyboardShortcutLocality;
	MigrationErrorKind: typeof MigrationErrorKind;
	ModifierKey: typeof ModifierKey;
	NodeExtensionsErrorCode: typeof NodeExtensionsErrorCode;
	NodeExtensionsRepository: {
		new (...args: unknown[]): NativeNodeExtensionsRepository;
	};
	NoteErrorCode: typeof NoteErrorCode;
	NotesRepository: { new (...args: unknown[]): NativeNotesRepository };
	OrgPackErrorCode: typeof OrgPackErrorCode;
	OrgPacksRepository: { new (...args: unknown[]): NativeOrgPacksRepository };
	PendingTokenErrorCode: typeof PendingTokenErrorCode;
	PendingTokensRepository: {
		new (...args: unknown[]): NativePendingTokensRepository;
	};
	Platform: typeof Platform;
	QuickLinkErrorCode: typeof QuickLinkErrorCode;
	QuicklinksRepository: {
		new (...args: unknown[]): NativeQuicklinksRepository;
	};
	ScreenshotCategory: typeof ScreenshotCategory;
	ScreenshotErrorCode: typeof ScreenshotErrorCode;
	ScreenshotsRepository: {
		new (...args: unknown[]): NativeScreenshotsRepository;
	};
	SettingsErrorCode: typeof SettingsErrorCode;
	SettingsRepository: { new (...args: unknown[]): NativeSettingsRepository };
	SnippetErrorCode: typeof SnippetErrorCode;
	SnippetsRepository: { new (...args: unknown[]): NativeSnippetsRepository };
	subscribeToWindowCloseOnWindows: UnverifiedNativeMethod;
	SyncAgent: {
		new (...args: unknown[]): NativeSyncAgent;
		setLogger: UnverifiedNativeMethod;
	};
	SyncAgentColumnStrategy: typeof SyncAgentColumnStrategy;
	TranslateCustomCommandErrorCode: typeof TranslateCustomCommandErrorCode;
	TranslateCustomCommandsRepository: {
		new (...args: unknown[]): NativeTranslateCustomCommandsRepository;
	};
	UserActivityErrorCode: typeof UserActivityErrorCode;
	UserActivityRepository: {
		new (...args: unknown[]): NativeUserActivityRepository;
	};
	UserActivityType: typeof UserActivityType;
	UserDefaultsErrorCode: typeof UserDefaultsErrorCode;
	UserDefaultsRepository: {
		new (...args: unknown[]): NativeUserDefaultsRepository;
	};
	WindowManagementErrorCode: typeof WindowManagementErrorCode;
	WindowManagementRepository: {
		new (...args: unknown[]): NativeWindowManagementRepository;
	};
	WindowsRunCommandErrorCode: typeof WindowsRunCommandErrorCode;
	WindowsRunCommandsRepository: {
		new (...args: unknown[]): NativeWindowsRunCommandsRepository;
	};
};
